---
# tasks file for node_exporter
- name: Download and unarchive node_exporter into temporary location.
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  when: >

- name: Move node_exporter binary.
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart node_exporter

- name: Create node_exporter user.
  user:
    name: "node_exporter"
    shell: "/sbin/nologin"
    state: present

- name: Copy the node_exporter systemd unit file.
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    mode: 0644
  register: node_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart node_exporter
  when: node_exporter_service is changed

- name: Ensure node_exporter is running and enabled at boot.
  service:
    name: node_exporter
    state: "{{ node_exporter_state }}"
    enabled: "{{ node_exporter_enabled }}"
